# Generated by Django 4.1 on 2023-09-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0004_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
    ]
